<?php

namespace Tests;

use Igrejanet\GerenciaNet\PaymentLinkCreator;
use PHPUnit\Framework\TestCase;

class PaymentLinkCreatorTest extends TestCase
{
    use Dependencies;

    /**
     * @var int
     */
    protected $charge_id;

    /**
     * @throws \Exception
     */
    public function setUp()
    {
        $this->charge_id = $this->createChargeId();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     * @throws
     */
    public function create_payment_link()
    {
        $charge_id      = $this->charge_id;
        $gerencianet    = $this->getGerencianet();
        $paymentLink    = $this->getPaymentLink();

        $creator    = new PaymentLinkCreator($gerencianet);
        $response   = $creator->createLink($charge_id, $paymentLink);

        $this->assertInternalType('array', $response);
        $this->assertArrayHasKey('payment_url', $response);
    }

    /**
     * @test
     * @throws \Igrejanet\GerenciaNet\Exceptions\InvalidPaymentTypeException
     */
    public function update_payment_link()
    {
        $gerencianet    = $this->getGerencianet();
        $paymentLink    = $this->getPaymentLink();

        $creator    = new PaymentLinkCreator($gerencianet);
        $response   = $creator->createLink($this->charge_id, $paymentLink);

        $link = $creator->createLink($this->charge_id, $paymentLink, true);

        $this->assertInternalType('array', $link);
        $this->assertArrayHasKey('payment_url', $link);
    }
}
